name: Auto Apply Jobs

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Scrape & Filter Dice Jobs"]
    types:
      - completed


permissions:
  contents: write

jobs:
  auto_apply:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Chrome 136 and Chromedriver
      run: |
        set -e
        sudo apt-get update
        sudo apt-get install -y wget unzip curl
        wget https://storage.googleapis.com/chrome-for-testing-public/136.0.7103.94/linux64/chrome-linux64.zip
        unzip -q chrome-linux64.zip
        sudo mv chrome-linux64 /opt/chrome
        sudo ln -sf /opt/chrome/chrome /usr/bin/google-chrome
        wget https://storage.googleapis.com/chrome-for-testing-public/136.0.7103.94/linux64/chromedriver-linux64.zip
        unzip -q chromedriver-linux64.zip
        sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver
        google-chrome --version
        chromedriver --version

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt

    - name: Run auto_apply.py
      env:
        APPLY_EMAIL: ${{ secrets.APPLY_EMAIL }}
        APPLY_PASSWORD: ${{ secrets.APPLY_PASSWORD }}
      run: python src/apply_jobs.py

    - name: Commit and push updated final_ml_jobs.csv
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add output/final_ml_jobs.csv output/logs/*

        if git diff --cached --quiet; then
          echo "No changes to commit."
        else
          git commit -m "✅ Auto-applied jobs and updated final_ml_jobs.csv"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
        fi