name: Auto Stealth

on:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: lock-stealth          # <-- shared with Scrape (see below)
  cancel-in-progress: false

jobs:
  auto_apply:
    runs-on: [self-hosted, dice-runner]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0

    - run: echo "🟢 Triggered by ${{ github.event_name }} on ${{ github.ref }}"

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt

    - name: Run stealth_apply.py
      env:
        APPLY_EMAIL: ${{ secrets.APPLY_EMAIL }}
        APPLY_PASSWORD: ${{ secrets.APPLY_PASSWORD }}
        APPLY_PROCESS_FAILED:  ${{ secrets.APPLY_PROCESS_FAILED }}
      run: python src/stealth_apply.py

    - name: Commit and push updated final_ml_jobs.csv
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add output/final_ml_jobs.csv output/logs/*

        if git diff --cached --quiet; then
          echo "✅ No changes to commit."
        else
          git commit -m "✅ Auto-applied jobs and updated final_ml_jobs.csv"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
        fi
